services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: moolahturtle-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
